package View;



import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author fuyun
 */
public class Cruises extends javax.swing.JFrame {

    /**
     * Creates new form Cruise
     */
    public Cruises() {

        initComponents();

        this.setVisible(true);
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Fu Yun
    private void initComponents() {
        jMenuBar1 = new JMenuBar();
        Query = new JMenu();
        Passengers = new JCheckBoxMenuItem();
        Cruises = new JCheckBoxMenuItem();
        Sailors = new JCheckBoxMenuItem();
        jPanel1 = new JPanel();
        port4 = new JCheckBox();
        CruiseSearch = new JButton();
        port3 = new JCheckBox();
        jLabel1 = new JLabel();
        port1 = new JCheckBox();
        port2 = new JCheckBox();
        jScrollPane1 = new JScrollPane();
        CruiseTable = new JTable();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container contentPane = getContentPane();
        contentPane.setLayout(new GridBagLayout());

        //======== jMenuBar1 ========
        {

            //======== Query ========
            {
                Query.setText("Query");

                //---- Passengers ----
                Passengers.setSelected(true);
                Passengers.setText("Passengers");
                Passengers.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        PassengersActionPerformed(e);
                    }
                });
                Query.add(Passengers);

                //---- Cruises ----
                Cruises.setSelected(true);
                Cruises.setText("Cruises");
                Cruises.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        CruisesActionPerformed(e);
                    }
                });
                Query.add(Cruises);

                //---- Sailors ----
                Sailors.setSelected(true);
                Sailors.setText("Sailors");
                Sailors.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        SailorsActionPerformed(e);
                    }
                });
                Query.add(Sailors);
            }
            jMenuBar1.add(Query);
        }
        setJMenuBar(jMenuBar1);

        //======== jPanel1 ========
        {

            // JFormDesigner evaluation mark
            jPanel1.setBorder(new javax.swing.border.CompoundBorder(
                new javax.swing.border.TitledBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0),
                    "JFormDesigner Evaluation", javax.swing.border.TitledBorder.CENTER,
                    javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    java.awt.Color.red), jPanel1.getBorder())); jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener(){public void propertyChange(java.beans.PropertyChangeEvent e){if("border".equals(e.getPropertyName()))throw new RuntimeException();}});


            //---- port4 ----
            port4.setText("port 4");

            //---- CruiseSearch ----
            CruiseSearch.setText("Search");
            CruiseSearch.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    CruiseSearchActionPerformed(e);
                }
            });

            //---- port3 ----
            port3.setText("port 3");

            //---- jLabel1 ----
            jLabel1.setText("Find the ports of cruises");

            //---- port1 ----
            port1.setText("port 1");
            port1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    port1ActionPerformed(e);
                }
            });

            //---- port2 ----
            port2.setText("port 2");

            //======== jScrollPane1 ========
            {

                //---- CruiseTable ----
                CruiseTable.setModel(new DefaultTableModel(
                    new Object[][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                    },
                    new String[] {
                        "Cruise ID", "Ship ID", "Port 1", "Port 2", "Port 3", "Port 4"
                    }
                ));
                CruiseTable.setSurrendersFocusOnKeystroke(true);
                jScrollPane1.setViewportView(CruiseTable);
            }

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(port1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(port2)
                        .addGap(18, 18, 18)
                        .addComponent(port3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(port4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CruiseSearch)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 588, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(port1)
                            .addComponent(port2)
                            .addComponent(port3)
                            .addComponent(port4)
                            .addComponent(CruiseSearch))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 260, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );
        }
        contentPane.add(jPanel1, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
            GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
            new Insets(6, 15, 17, 31), 9, 0));
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void PassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassengersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassengersActionPerformed

    private void CruisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CruisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CruisesActionPerformed

    private void SailorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SailorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SailorsActionPerformed

    private void port1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_port1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_port1ActionPerformed

    private void CruiseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CruiseSearchActionPerformed
        // TODO add your handling code here:
        String[] name = {"Cruise ID","Ship ID","Port 1","Port 2", "Port 3", "Port 4"};
        String[][] data = new String[300][6];//此处略去赋值操作
        DefaultTableModel defaultmodel = new DefaultTableModel(data, name);
        CruiseTable.setModel(defaultmodel);
        for(int i=0; i<CruiseTable.getRowCount(); i++){
            CruiseTable.setValueAt(null, i, 0);
            CruiseTable.setValueAt(null, i, 1);
            CruiseTable.setValueAt(null, i, 2);
            CruiseTable.setValueAt(null, i, 3);
        }
//        try{
        for(int i=0; i<SearchPage.db.getCruiseAll().size(); i++){

            CruiseTable.setValueAt(SearchPage.db.getCruiseAll().get(i).getID(), i, 0);
            CruiseTable.setValueAt(SearchPage.db.getCruiseAll().get(i).getShipID(), i, 1);
            CruiseTable.setValueAt(SearchPage.db.getCruiseAll().get(i).getPort1(), i, 2);
            CruiseTable.setValueAt(SearchPage.db.getCruiseAll().get(i).getPort2(), i, 3);
            CruiseTable.setValueAt(SearchPage.db.getCruiseAll().get(i).getPort3(), i, 4);
            CruiseTable.setValueAt(SearchPage.db.getCruiseAll().get(i).getPort4(), i, 5);
        }
//        } catch (SQLException ex) {
//                Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
//            }
    }//GEN-LAST:event_CruiseSearchActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Cruise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Cruise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Cruise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Cruise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Cruise().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Fu Yun
    private JMenuBar jMenuBar1;
    private JMenu Query;
    private JCheckBoxMenuItem Passengers;
    private JCheckBoxMenuItem Cruises;
    private JCheckBoxMenuItem Sailors;
    private JPanel jPanel1;
    private JCheckBox port4;
    private JButton CruiseSearch;
    private JCheckBox port3;
    private JLabel jLabel1;
    private JCheckBox port1;
    private JCheckBox port2;
    private JScrollPane jScrollPane1;
    private JTable CruiseTable;
    // End of variables declaration//GEN-END:variables
}
